# N64Recomp configuration for Rampage 2: Universal Tour (N2PE)
# USA v1.0 - CRC: 673D099B / A4C808DE

[input]
entrypoint = 0x80000400
symbols_file_path = "symbols/rampage2_ut_syms.toml"
rom_file_path = "Rampage 2 - Universal Tour (U) [!].z64"
output_func_path = "RecompiledFuncs_R2"

[patches]
ignored = [
    "func_8007FB9C",
    "func_8007FB70",
    "func_8007F5E8",
    "func_8007F590",
    "func_8007F588",
    "func_8007F568",
    "func_8007EC58",
    "func_8007EC10",
    "func_8007EBE8",
    "func_8007E76C",
    "func_8007E6B0",
    "func_8007E594",
    "func_8007E540",
    "func_800762A0",
    "func_80076250",
    "func_80076220",
    "func_800760C0",
    "func_80076050",
    "func_80076000",
    "func_80075FE0",
    "func_80075B3C",
    "func_800758EC",
    "func_80075360",
    "func_80072BD0",
    "func_80070460",
    "func_80070430",
    "func_800703E0",
    "func_8007035C",
    "func_800702D0",
    "func_8005B620",
    "func_8000FDB8",
    "func_80008B40",
    "func_80005E08",
    "func_80005D90",
    "func_80005AE0",
    "func_80005A78",
    "func_800058E0",
    "func_80005718",
]
stubs = [
    "stub_80000000",
    "stub_80303030",
    "stub_80543054",
    "stub_80643068",
    "stub_80703070",
    "stub_80E59AB4",
    "stub_81BC31B4",
    "stub_84000000",
    "stub_84001000",
    "stub_8400103C",
    "stub_840010C8",
    "stub_840010E4",
    "stub_84001104",
    "stub_84001120",
    "stub_84001150",
    "stub_84001184",
    "stub_840011B0",
    "stub_840011B8",
    "stub_840015F4",
    "stub_84001658",
    "stub_84001680",
    "stub_84001694",
    "stub_84001FC4",
    "stub_84001FD4",
    "stub_84001FD8",
    "stub_84004B40",
    "stub_84004B48",
    "stub_84004B50",
    "stub_84004B58",
    "stub_84004B60",
    "stub_84004B68",
    "stub_84004B70",
    "stub_84004B78",
    "stub_84004B80",
    "stub_84004B88",
    "stub_84004B90",
    "stub_84004B98",
    "stub_84004BA0",
    "stub_84004BA8",
    "stub_84004BB0",
    "stub_84004BB8",
    "stub_84004BC0",
    "stub_84004BC8",
    "stub_84004BD0",
    "stub_84004BD8",
    "stub_84004BE0",
    "stub_84004BE8",
    "stub_84004BF0",
    "stub_84004BF8",
    "stub_84004C00",
    "stub_84004C08",
    "stub_84004C10",
    "stub_84004C18",
    "stub_84004C20",
    "stub_84004C28",
    "stub_84004C30",
    "stub_84004C38",
    "stub_84004C40",
    "stub_84004C48",
    "stub_84004C50",
    "stub_84004C58",
    "stub_84004C60",
    "stub_84004C68",
    "stub_84004C70",
    "stub_84004C78",
    "stub_84004C80",
    "stub_84004C88",
    "stub_84004C90",
    "stub_84004C98",
    "stub_84004CA0",
    "stub_84004CA8",
    "stub_84004CB0",
    "stub_84004CB8",
    "stub_84004CC0",
    "stub_84004CC8",
    "stub_84004CD0",
    "stub_84004CD8",
    "stub_84004CE0",
    "stub_84004CE8",
    "stub_84004CF0",
    "stub_84004CF8",
    "stub_84004D00",
    "stub_84004D08",
    "stub_84004D10",
    "stub_84004D18",
    "stub_84004D20",
    "stub_84004D28",
    "stub_84004D30",
    "stub_84004D38",
    "stub_84004D40",
    "stub_84004D48",
    "stub_84004D50",
    "stub_84004D58",
    "stub_84004D60",
    "stub_84004D68",
    "stub_84004D78",
    "stub_84004D80",
    "stub_84004D88",
    "stub_84004D90",
    "stub_84004D98",
    "stub_84004DA0",
    "stub_84004DA8",
    "stub_84004DB0",
    "stub_84004DB8",
    "stub_84004DC0",
    "stub_84004DC8",
    "stub_84004DD0",
    "stub_84004DD8",
    "stub_84004DE0",
    "stub_84004DE8",
    "stub_84004DF0",
    "stub_84004DF8",
    "stub_84004E08",
    "stub_84004E10",
    "stub_84004E18",
    "stub_84004E20",
    "stub_84004E28",
    "stub_84004E30",
    "stub_84004E38",
    "stub_84004E40",
    "stub_84004E48",
    "stub_84004E50",
    "stub_84004E58",
    "stub_84004E60",
    "stub_84004E68",
    "stub_84004E70",
    "stub_84004E78",
    "stub_84004E80",
    "stub_84004E88",
    "stub_84004E90",
    "stub_84004E98",
    "stub_84004EA0",
    "stub_84004EA8",
    "stub_84004EB0",
    "stub_84004EB8",
    "stub_84004EC0",
    "stub_84004EC8",
    "stub_84004ED0",
    "stub_84004ED8",
    "stub_84004EE0",
    "stub_84004EE8",
    "stub_84004EF0",
    "stub_84004EF8",
    "stub_84004F00",
    "stub_84004F08",
    "stub_84004F10",
    "stub_84004F18",
    "stub_84004F20",
    "stub_84004F28",
    "stub_84004F30",
    "stub_84004F38",
    "stub_84004F40",
    "stub_84004F48",
    "stub_84004F50",
    "stub_84004F58",
    "stub_84004F60",
    "stub_84004F68",
    "stub_84004F70",
    "stub_84004F78",
    "stub_84004F80",
    "stub_84004F88",
    "stub_84004F90",
    "stub_84004F98",
    "stub_84004FA0",
    "stub_84004FA8",
    "stub_84004FB0",
    "stub_84004FB8",
    "stub_84004FC0",
    "stub_84004FC8",
    "stub_84004FD0",
    "stub_84004FD8",
    "stub_84004FE0",
    "stub_84004FE8",
    "stub_84004FF0",
    "stub_84004FF8",
    "stub_84005000",
    "stub_84005008",
    "stub_84005010",
    "stub_84005018",
    "stub_84005020",
    "stub_84005028",
    "stub_84005030",
    "stub_84005038",
    "stub_84005040",
    "stub_84005048",
    "stub_84005050",
    "stub_84005058",
    "stub_84005060",
    "stub_84005068",
    "stub_84005070",
    "stub_84005078",
    "stub_84005080",
    "stub_84005088",
    "stub_84005090",
    "stub_84005098",
    "stub_840050A0",
    "stub_840050A8",
    "stub_840050B0",
    "stub_840050B8",
    "stub_840050C0",
    "stub_840050C8",
    "stub_840050D0",
    "stub_84005108",
    "stub_84005110",
    "stub_84005118",
    "stub_84005120",
    "stub_84005128",
    "stub_84005130",
    "stub_84005138",
    "stub_84005140",
    "stub_84005148",
    "stub_84005150",
    "stub_84005158",
    "stub_84005160",
    "stub_84005168",
    "stub_84005170",
    "stub_84005178",
    "stub_84005180",
    "stub_84005188",
    "stub_84005190",
    "stub_84005198",
    "stub_840051A0",
    "stub_840051A8",
    "stub_840051B8",
    "stub_840051C0",
    "stub_840051C8",
    "stub_840051D0",
    "stub_840051D8",
    "stub_840051E0",
    "stub_840051E8",
    "stub_840051F0",
    "stub_840051F8",
    "stub_84005200",
    "stub_84005208",
    "stub_84005210",
    "stub_84005218",
    "stub_84005220",
    "stub_84005228",
    "stub_84005230",
    "stub_84005238",
    "stub_84005240",
    "stub_84005248",
    "stub_84005250",
    "stub_84005258",
    "stub_84005260",
    "stub_84005268",
    "stub_84005270",
    "stub_84005278",
    "stub_84005280",
    "stub_84005288",
    "stub_84005290",
    "stub_84005298",
    "stub_840052A0",
    "stub_840052A8",
    "stub_840052B0",
    "stub_840052B8",
    "stub_840052C0",
    "stub_840052C8",
    "stub_840052D0",
    "stub_840052D8",
    "stub_840052E0",
    "stub_840052E8",
    "stub_840052F0",
    "stub_840052F8",
    "stub_84005300",
    "stub_84005308",
    "stub_84005310",
    "stub_84005318",
    "stub_84005320",
    "stub_84005328",
    "stub_84005330",
    "stub_84005338",
    "stub_84005340",
    "stub_84005348",
    "stub_84005350",
    "stub_84005358",
    "stub_84005360",
    "stub_84005368",
    "stub_84005370",
    "stub_84005378",
    "stub_84005380",
    "stub_84005388",
    "stub_84005390",
    "stub_84005398",
    "stub_840053A0",
    "stub_840053A8",
    "stub_840053B0",
    "stub_840053C0",
    "stub_840053C8",
    "stub_840053D0",
    "stub_840053D8",
    "stub_840053E0",
    "stub_840053E8",
    "stub_840053F0",
    "stub_840053F8",
    "stub_84005400",
    "stub_84005408",
    "stub_84005410",
    "stub_84005418",
    "stub_84005420",
    "stub_84005428",
    "stub_84005430",
    "stub_84005438",
    "stub_84005440",
    "stub_84005448",
    "stub_84005450",
    "stub_84005458",
    "stub_84005460",
    "stub_84005468",
    "stub_84005470",
    "stub_84005478",
    "stub_84005480",
    "stub_84005488",
    "stub_84005490",
    "stub_84005498",
    "stub_840054A0",
    "stub_840054A8",
    "stub_840054B0",
    "stub_840054B8",
    "stub_840054C0",
    "stub_840054C8",
    "stub_840054D0",
    "stub_840054D8",
    "stub_840054E0",
    "stub_840054E8",
    "stub_840054F0",
    "stub_840054F8",
    "stub_84005500",
    "stub_84005508",
    "stub_84005510",
    "stub_84005518",
    "stub_84005520",
    "stub_84005528",
    "stub_84005530",
    "stub_84005548",
    "stub_84005550",
    "stub_84005558",
    "stub_84005560",
    "stub_84005568",
    "stub_84005570",
    "stub_84005578",
    "stub_84005580",
    "stub_84005588",
    "stub_84005590",
    "stub_84005598",
    "stub_840055A0",
    "stub_840055A8",
    "stub_840055B8",
    "stub_840055C0",
    "stub_840055C8",
    "stub_840055D0",
    "stub_840055D8",
    "stub_840055E0",
    "stub_840055E8",
    "stub_840055F0",
    "stub_840055F8",
    "stub_84005600",
    "stub_84005608",
    "stub_84005610",
    "stub_84005618",
    "stub_84005620",
    "stub_84005628",
    "stub_84005630",
    "stub_84005638",
    "stub_84005640",
    "stub_84005648",
    "stub_84005650",
    "stub_84005658",
    "stub_84005660",
    "stub_84005668",
    "stub_84005670",
    "stub_84005678",
    "stub_84008C30",
    "stub_84008C38",
    "stub_84008C40",
    "stub_84008C48",
    "stub_84008C50",
    "stub_84008C58",
    "stub_84008C60",
    "stub_84008C68",
    "stub_84008C70",
    "stub_84008C78",
    "stub_84008C80",
    "stub_84008C88",
    "stub_84008C90",
    "stub_84008C98",
    "stub_84008CA0",
    "stub_84008CA8",
    "stub_84008CB0",
    "stub_84008CB8",
    "stub_84008CC0",
    "stub_84008CC8",
    "stub_84008CD0",
    "stub_84008CD8",
    "stub_84008CE0",
    "stub_84008CE8",
    "stub_84008CF0",
    "stub_84008CF8",
    "stub_84008D00",
    "stub_84008D08",
    "stub_84008D10",
    "stub_84008D18",
    "stub_84008D20",
    "stub_84008D28",
    "stub_84008D30",
    "stub_84009F28",
    "stub_84009F30",
    "stub_84009F38",
    "stub_84009F40",
    "stub_84009F48",
    "stub_84009F50",
    "stub_84009F58",
    "stub_84009F60",
    "stub_8400F640",
    "stub_8400F648",
    "stub_8400F650",
    "stub_8400F658",
    "stub_8400FDC8",
    "stub_8400FDD0",
    "stub_8400FDD8",
    "stub_8400FDE0",
    "stub_8400FDE8",
    "stub_8400FDF0",
    "stub_8400FDF8",
    "stub_8400FE00",
    "stub_851BFF7C",
    "stub_88000000",
    "stub_880003D8",
    "stub_880003E0",
    "stub_880003E8",
    "stub_880003F0",
    "stub_880003F8",
    "stub_88000400",
    "stub_88000408",
    "stub_88000410",
    "stub_88000418",
    "stub_88000420",
    "stub_88000428",
    "stub_88000430",
    "stub_88000438",
    "stub_88000440",
    "stub_88000448",
    "stub_88000450",
    "stub_88000458",
    "stub_88000460",
    "stub_88000468",
    "stub_88000470",
    "stub_88000478",
    "stub_88000480",
    "stub_88000488",
    "stub_88000490",
    "stub_88000498",
    "stub_880004A0",
    "stub_880004A8",
    "stub_880004B0",
    "stub_880004B8",
    "stub_880004C0",
    "stub_880004C8",
    "stub_880004D0",
    "stub_880004D8",
    "stub_880004E0",
    "stub_880004E8",
    "stub_880004F0",
    "stub_880004F8",
    "stub_88000500",
    "stub_88000508",
    "stub_88000510",
    "stub_88000518",
    "stub_88000520",
    "stub_88000528",
    "stub_88000530",
    "stub_88000538",
    "stub_88000540",
    "stub_88000550",
    "stub_88000558",
    "stub_88000560",
    "stub_88000568",
    "stub_88000570",
    "stub_88000578",
    "stub_88000580",
    "stub_88000588",
    "stub_88000590",
    "stub_88000598",
    "stub_880005A0",
    "stub_880005A8",
    "stub_880005B0",
    "stub_880005B8",
    "stub_880005C0",
    "stub_880005C8",
    "stub_880005D0",
    "stub_880005E0",
    "stub_880005E8",
    "stub_880005F0",
    "stub_880005F8",
    "stub_88000600",
    "stub_88000608",
    "stub_88000610",
    "stub_88000618",
    "stub_88000620",
    "stub_88000628",
    "stub_88000630",
    "stub_88000638",
    "stub_88000640",
    "stub_88000648",
    "stub_88000650",
    "stub_88000658",
    "stub_88000660",
    "stub_88000668",
    "stub_88000670",
    "stub_88000678",
    "stub_88000680",
    "stub_88000688",
    "stub_88000690",
    "stub_88000698",
    "stub_880006A0",
    "stub_880006A8",
    "stub_880006B0",
    "stub_880006B8",
    "stub_880006C0",
    "stub_880006C8",
    "stub_880006D0",
    "stub_880006D8",
    "stub_880006E0",
    "stub_880006E8",
    "stub_880006F0",
    "stub_880006F8",
    "stub_88000700",
    "stub_88000708",
    "stub_88000710",
    "stub_88000718",
    "stub_88000720",
    "stub_88000728",
    "stub_88000730",
    "stub_88000738",
    "stub_88000740",
    "stub_88000748",
    "stub_88000750",
    "stub_88000758",
    "stub_88000760",
    "stub_88000768",
    "stub_88000770",
    "stub_88000778",
    "stub_88000780",
    "stub_88000788",
    "stub_88000790",
    "stub_88000798",
    "stub_880007A0",
    "stub_880007A8",
    "stub_880007B0",
    "stub_880007B8",
    "stub_880007C0",
    "stub_880007C8",
    "stub_880007D0",
    "stub_880007D8",
    "stub_880007E0",
    "stub_880007E8",
    "stub_880007F0",
    "stub_880007F8",
    "stub_88000800",
    "stub_88000808",
    "stub_88000810",
    "stub_88000818",
    "stub_88000820",
    "stub_88000828",
    "stub_88000830",
    "stub_88000838",
    "stub_88000840",
    "stub_88000848",
    "stub_88000850",
    "stub_88000858",
    "stub_88000860",
    "stub_88000868",
    "stub_88000870",
    "stub_88000878",
    "stub_88000880",
    "stub_88000888",
    "stub_88000890",
    "stub_88000898",
    "stub_880008A0",
    "stub_880008A8",
    "stub_880008B0",
    "stub_880008B8",
    "stub_880008C0",
    "stub_880008C8",
    "stub_880008D0",
    "stub_880008D8",
    "stub_880008E0",
    "stub_880008E8",
    "stub_880008F0",
    "stub_880008F8",
    "stub_88000900",
    "stub_88000908",
    "stub_88000910",
    "stub_88000948",
    "stub_88000950",
    "stub_88000958",
    "stub_88000960",
    "stub_88000968",
    "stub_88000970",
    "stub_88000978",
    "stub_88000980",
    "stub_88000988",
    "stub_88000990",
    "stub_88000998",
    "stub_880009A0",
    "stub_880009A8",
    "stub_880009B0",
    "stub_880009B8",
    "stub_880009C0",
    "stub_880009C8",
    "stub_880009D0",
    "stub_880009D8",
    "stub_880009E0",
    "stub_880009E8",
    "stub_880009F8",
    "stub_88000A00",
    "stub_88000A08",
    "stub_88000A10",
    "stub_88000A18",
    "stub_88000A20",
    "stub_88000A28",
    "stub_88000A30",
    "stub_88000A38",
    "stub_88000A40",
    "stub_88000A48",
    "stub_88000A50",
    "stub_88000A58",
    "stub_88000A60",
    "stub_88000A68",
    "stub_88000A70",
    "stub_88000A78",
    "stub_88000A80",
    "stub_88000A88",
    "stub_88000A90",
    "stub_88000A98",
    "stub_88000AA0",
    "stub_88000AA8",
    "stub_88000AB0",
    "stub_88000AB8",
    "stub_88000AC0",
    "stub_88000AC8",
    "stub_88000AD0",
    "stub_88000AD8",
    "stub_88000AE0",
    "stub_88000AE8",
    "stub_88000AF0",
    "stub_88000AF8",
    "stub_88000B00",
    "stub_88000B08",
    "stub_88000B10",
    "stub_88000B18",
    "stub_88000B20",
    "stub_88000B28",
    "stub_88000B30",
    "stub_88000B38",
    "stub_88000B40",
    "stub_88000B48",
    "stub_88000B50",
    "stub_88000B58",
    "stub_88000B60",
    "stub_88000B68",
    "stub_88000B70",
    "stub_88000B78",
    "stub_88000B80",
    "stub_88000B88",
    "stub_88000B90",
    "stub_88000B98",
    "stub_88000BA0",
    "stub_88000BA8",
    "stub_88000BB0",
    "stub_88000BC0",
    "stub_88000BC8",
    "stub_88000BD0",
    "stub_88000BD8",
    "stub_88000BE0",
    "stub_88000BE8",
    "stub_88000BF0",
    "stub_88000BF8",
    "stub_88000C00",
    "stub_88000C08",
    "stub_88000C10",
    "stub_88000C18",
    "stub_88000C20",
    "stub_88000C28",
    "stub_88000C30",
    "stub_88000C38",
    "stub_88000C40",
    "stub_88000C48",
    "stub_88000C50",
    "stub_88000C58",
    "stub_88000C60",
    "stub_88000C68",
    "stub_88000C70",
    "stub_88000C78",
    "stub_88000C80",
    "stub_88000C88",
    "stub_88000C90",
    "stub_88000C98",
    "stub_88000CA0",
    "stub_88000CA8",
    "stub_88000CB0",
    "stub_88000CB8",
    "stub_88000CC0",
    "stub_88000CC8",
    "stub_88000CD0",
    "stub_88000CD8",
    "stub_88000CE0",
    "stub_88000CE8",
    "stub_88000CF0",
    "stub_88000CF8",
    "stub_88000D00",
    "stub_88000D08",
    "stub_88000D10",
    "stub_88000D18",
    "stub_88000D20",
    "stub_88000D28",
    "stub_88000D30",
    "stub_88000D48",
    "stub_88000D50",
    "stub_88000D58",
    "stub_88000D60",
    "stub_88000D68",
    "stub_88000D70",
    "stub_88000D78",
    "stub_88000D80",
    "stub_88000D88",
    "stub_88000D90",
    "stub_88000D98",
    "stub_88000DA0",
    "stub_88000DA8",
    "stub_88000DB8",
    "stub_88000DC0",
    "stub_88000DC8",
    "stub_88000DD0",
    "stub_88000DD8",
    "stub_88000DE0",
    "stub_88000DE8",
    "stub_88000DF0",
    "stub_88000DF8",
    "stub_88000E00",
    "stub_88000E08",
    "stub_88000E10",
    "stub_88000E18",
    "stub_88000E20",
    "stub_88000E28",
    "stub_88000E30",
    "stub_88000E38",
    "stub_88000E40",
    "stub_88000E48",
    "stub_88000E50",
    "stub_88000E58",
    "stub_88000E60",
    "stub_88000E68",
    "stub_88000E70",
    "stub_88000E78",
    "stub_88000E80",
    "stub_88000E88",
    "stub_88000E90",
    "stub_88000E98",
    "stub_88000EA0",
    "stub_88000EA8",
    "stub_88000EB0",
    "stub_88000EB8",
    "stub_88000EC0",
    "stub_88000EC8",
    "stub_88000ED0",
    "stub_88000ED8",
    "stub_88000EE0",
    "stub_88000EE8",
    "stub_88000EF0",
    "stub_88000EF8",
    "stub_88000F00",
    "stub_88000F08",
    "stub_88000F10",
    "stub_88008880",
    "stub_88008888",
    "stub_88008890",
    "stub_88008898",
    "stub_880088A0",
    "stub_880088A8",
    "stub_880088B0",
    "stub_880088B8",
    "stub_880088C0",
    "stub_880088C8",
    "stub_880088D0",
    "stub_880088D8",
    "stub_880088E0",
    "stub_880088E8",
    "stub_880088F0",
    "stub_880088F8",
    "stub_88008900",
    "stub_88008908",
    "stub_88008910",
    "stub_88008918",
    "stub_88008920",
    "stub_88008928",
    "stub_88008930",
    "stub_88008938",
    "stub_88008940",
    "stub_88008948",
    "stub_88008A48",
    "stub_88008A50",
    "stub_88008A58",
    "stub_88008A60",
    "stub_88008A68",
    "stub_88008A70",
    "stub_88008A78",
    "stub_8800FA20",
    "stub_8800FA28",
    "stub_8800FA30",
    "stub_8800FA38",
    "stub_8800FD08",
    "stub_8800FD10",
    "stub_8800FD18",
    "stub_8800FD20",
    "stub_8800FD28",
    "stub_8800FD30",
    "stub_8800FD38",
    "stub_8800FD40",
    "stub_88C52FF8",
    "stub_88E03294",
    "stub_897FFF60",
    "stub_8A53B8E4",
    "stub_8C000000",
    "stub_8DFC4200",
    "stub_8E0FFF40",
    "stub_8FEBC018",
    "stub_8FFC7FFC",
    "stub_8FFFFFFC",
]
