# N64Recomp configuration for Rampage: World Tour (NRPE)
# USA v1.0 - CRC: C29FF9E4 / 264BFE7D

[input]
entrypoint = 0x80000400
symbols_file_path = "symbols/rampage_wt_syms.toml"
rom_file_path = "Rampage - World Tour (U) [!].z64"
output_func_path = "RecompiledFuncs_WT"

[patches]
ignored = [
    "func_8007623C",
    "func_80076210",
    "func_80075C88",
    "func_80075C30",
    "func_80075C28",
    "func_80075C08",
    "func_80075300",
    "func_800752B8",
    "func_80075290",
    "func_80074E14",
    "func_80074D58",
    "func_80074C34",
    "func_80074BE0",
    "func_8006FD20",
    "func_8006E490",
    "func_8006E074",
    "func_8006B570",
    "func_8006B318",
    "func_8005DE4C",
    "func_8002DA90",
]
stubs = [
    "stub_80000000",
    "stub_801378DC",
    "stub_80137FEC",
    "stub_8013858C",
    "stub_80138934",
    "stub_80138C30",
    "stub_80138EFC",
    "stub_80139D7C",
    "stub_8013A128",
    "stub_8013A650",
    "stub_8013A89C",
    "stub_8013ABB0",
    "stub_8013AE84",
    "stub_8013B0D4",
    "stub_8013B3B4",
    "stub_8013B620",
    "stub_8013B668",
    "stub_8013BD28",
    "stub_8013E750",
    "stub_8013E788",
    "stub_80142BCC",
    "stub_801430E0",
    "stub_801431A4",
    "stub_801436F0",
    "stub_8014376C",
    "stub_801459C8",
    "stub_8014F280",
    "stub_8014F648",
    "stub_802C1028",
    "stub_80303030",
    "stub_80543054",
    "stub_80643068",
    "stub_80703070",
    "stub_80842084",
    "stub_80842108",
    "stub_80E59AB4",
    "stub_81002000",
    "stub_81042080",
    "stub_81043100",
    "stub_8109FF80",
    "stub_81800030",
    "stub_81880200",
    "stub_818C0000",
    "stub_818C1084",
    "stub_818C1180",
    "stub_818C2108",
    "stub_818C4184",
    "stub_818C5000",
    "stub_818C5294",
    "stub_818C5328",
    "stub_818C7000",
    "stub_818C8420",
    "stub_818C9000",
    "stub_818C9398",
    "stub_818C94A4",
    "stub_818CA41C",
    "stub_818CF7BC",
    "stub_818D394C",
    "stub_81900280",
    "stub_819010A0",
    "stub_81902108",
    "stub_81906108",
    "stub_8194210C",
    "stub_81945108",
    "stub_8198C000",
    "stub_81A82124",
    "stub_81AC2124",
    "stub_81BC31B4",
    "stub_82003104",
    "stub_8204C730",
    "stub_82082184",
    "stub_82090944",
    "stub_820C2108",
    "stub_820C2188",
    "stub_820CF7BC",
    "stub_820D5DFC",
    "stub_82101084",
    "stub_821C01A8",
    "stub_821C3198",
    "stub_821C3218",
    "stub_823C32BC",
    "stub_82845410",
    "stub_82881084",
    "stub_829C0084",
    "stub_829C2218",
    "stub_829C85B8",
    "stub_829D0944",
    "stub_829D8940",
    "stub_82A03204",
    "stub_82A04210",
    "stub_82A0520C",
    "stub_82A4528C",
    "stub_82AC31A4",
    "stub_82BC21B4",
    "stub_82BC2238",
    "stub_82C03340",
    "stub_82C10024",
    "stub_831C2208",
    "stub_8328329C",
    "stub_834032BC",
    "stub_83807280",
    "stub_83A02294",
    "stub_83B06290",
    "stub_83B433AC",
    "stub_83B44324",
    "stub_83E02260",
    "stub_83E04438",
    "stub_84000000",
    "stub_84001000",
    "stub_8400103C",
    "stub_840010C8",
    "stub_840010EC",
    "stub_8400110C",
    "stub_84001128",
    "stub_84001150",
    "stub_84001184",
    "stub_840011B0",
    "stub_840011C0",
    "stub_840015FC",
    "stub_84001660",
    "stub_84001688",
    "stub_8400169C",
    "stub_84001FC4",
    "stub_84001FD4",
    "stub_84001FD8",
    "stub_842C3188",
    "stub_842DF480",
    "stub_84306310",
    "stub_84342330",
    "stub_84350840",
    "stub_843D0840",
    "stub_84B08418",
    "stub_850C2488",
    "stub_851BFF7C",
    "stub_8541B194",
    "stub_854C8424",
    "stub_8584B498",
    "stub_85B08420",
    "stub_85CDC1A4",
    "stub_85D074AC",
    "stub_86802580",
    "stub_88000000",
    "stub_88F8963C",
    "stub_897FFF60",
    "stub_89F8CB74",
    "stub_8A8C2A08",
    "stub_8C000000",
    "stub_8C290000",
    "stub_8DFC4200",
    "stub_8E0FFF40",
    "stub_8FEBC018",
    "stub_8FFFFFFC",
]
